import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Header from "@/components/ui/header";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner"

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SensAI - AI Carrer Coach",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
            >

            {/* <header></header> */}
            <Header />


            <main className="min-h-screen">
              {children}
            </main>

            <Toaster  richColors />

            {/* <footer></footer> */}
            <footer  className="bg-muted/50 py-12">
              <div className="container mx-auto px-4 text-center">
                <p>Made by the Team SensAI</p>
              </div>
            </footer>
          </ThemeProvider>

      </body>
    </html>
    </ClerkProvider>
  );
}
